### ISSUE TITLE
citadel用老的吗

### ISSUE THREAD

**Issue by jasonjoo2010** [projecteru2/white-paper#5]
projecteru2&projecteru 一样？

**Comment by CMGS** [comment]
@jasonjoo2010 不一样，projecteru 是在芒果 TV 时期写的，目前已经脱坑了。2代的话 citadel 新版没开放出来，目前用的话用 cli 就行了。有一个一件单机脚本你可以试试 https://eru.sh/demo

**Comment by jasonjoo2010** [comment]
> @jasonjoo2010 不一样，projecteru 是在芒果 TV 时期写的，目前已经脱坑了。2代的话 citadel 新版没开放出来，目前用的话用 cli 就行了。有一个一件单机脚本你可以试试 https://eru.sh/demo

啊，没开放出来是没写完还是没脱敏？

没panel那肯定得准备一个………本来是想先写个lb的panel，发现新版支持etcd了，这个有开源计划吗？

**Comment by CMGS** [comment]
@jasonjoo2010 有其实还是有…但是周期太长了，我现在团队的话在 shopee 这边主要偏向于基础服务（靠 eru 部署 redis/mysql/pika/nginx/elb 等）所以应用层面上没花太多心思。因为做大一统的平台（其实就是抄青云）所以最终会有个新的「citadel」放出来，但 ETA 的话真保证不了。

**Comment by jasonjoo2010** [comment]
> @jasonjoo2010 有其实还是有…但是周期太长了，我现在团队的话在 shopee 这边主要偏向于基础服务（靠 eru 部署 redis/mysql/pika/nginx/elb 等）所以应用层面上没花太多心思。因为做大一统的平台（其实就是抄青云）所以最终会有个新的「citadel」放出来，但 ETA 的话真保证不了。

好的吧，还没正式开始入坑，所以目前的功能主要就是  集成+调度 ？那比如类似nginx的网站配置之类的控制台还是要自建咯？

**Comment by CMGS** [comment]
> > @jasonjoo2010 有其实还是有…但是周期太长了，我现在团队的话在 shopee 这边主要偏向于基础服务（靠 eru 部署 redis/mysql/pika/nginx/elb 等）所以应用层面上没花太多心思。因为做大一统的平台（其实就是抄青云）所以最终会有个新的「citadel」放出来，但 ETA 的话真保证不了。
> 
> 好的吧，还没正式开始入坑，所以目前的功能主要就是 集成+调度 ？那比如类似nginx的网站配置之类的控制台还是要自建咯？

恩，现在核心是只调度和一个穷人版的 PaaS （cli 项目）。对 nginx 网站配置其实也有，是用 cli publish 功能实现的…其实 citadel 上的功能在 cli 里面基本都实现了，但只能在 terminal 里面用

**Comment by jasonjoo2010** [comment]
> > > @jasonjoo2010 有其实还是有…但是周期太长了，我现在团队的话在 shopee 这边主要偏向于基础服务（靠 eru 部署 redis/mysql/pika/nginx/elb 等）所以应用层面上没花太多心思。因为做大一统的平台（其实就是抄青云）所以最终会有个新的「citadel」放出来，但 ETA 的话真保证不了。
> > 
> > 
> > 好的吧，还没正式开始入坑，所以目前的功能主要就是 集成+调度 ？那比如类似nginx的网站配置之类的控制台还是要自建咯？
> 
> 恩，现在核心是只调度和一个穷人版的 PaaS （cli 项目）。对 nginx 网站配置其实也有，是用 cli publish 功能实现的…其实 citadel 上的功能在 cli 里面基本都实现了，但只能在 terminal 里面用

好的，那我先搭个测试环境感受下要不要入坑

目前不用它来驱动业务？

**Comment by CMGS** [comment]
@jasonjoo2010 看怎么定义这个业务了…如果是产品后端的话，是可以驱动的。事实上通过 cli 可以部署任意的东西，后端，基础设施，带状态落地的程序（如 pika）都可以…ELB 作为一个简单版的 gateway 也是可以上产品线的。

**Comment by jasonjoo2010** [comment]
> @jasonjoo2010 看怎么定义这个业务了…如果是产品后端的话，是可以驱动的。事实上通过 cli 可以部署任意的东西，后端，基础设施，带状态落地的程序（如 pika）都可以…ELB 作为一个简单版的 gateway 也是可以上产品线的。

好的，我先看看，预期是解决好一些基础服务后，实际的业务项目能开放出去给业务团队去自行使用，减轻运维压力

**Comment by jasonjoo2010** [comment]
多谢啦

**Comment by CMGS** [comment]
@jasonjoo2010 客气，你可以邮箱联系我……我现在这个养老工作啊 - -
反正也在协助另外一家公司用 eru……

**Comment by jasonjoo2010** [comment]
> @jasonjoo2010 客气，你可以邮箱联系我……我现在这个养老工作啊 - -
> 反正也在协助另外一家公司用 eru……

哈哈，我就说这两年咋不活跃了

**Comment by CMGS** [comment]
@jasonjoo2010 哈哈更新一直有啦，你看 Core 的提交……不过因为换工作和重组团队，对于上面的 PaaS UI 支持停掉了……现在核心就是 core/agent/cli 加个 elb
